import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const countryCodes = [
  { code: 1, name: "United States" },
  { code: 44, name: "United Kingdom" },
  { code: 91, name: "India" },
  { code: 86, name: "China" },
  { code: 81, name: "Japan" },
  { code: 49, name: "Germany" },
  { code: 33, name: "France" },
  { code: 39, name: "Italy" },
  { code: 34, name: "Spain" },
  { code: 31, name: "Netherlands" },
  { code: 32, name: "Belgium" },
  { code: 41, name: "Switzerland" },
  { code: 46, name: "Sweden" },
  { code: 47, name: "Norway" },
  { code: 45, name: "Denmark" },
  { code: 358, name: "Finland" },
  { code: 48, name: "Poland" },
  { code: 420, name: "Czech Republic" },
  { code: 36, name: "Hungary" },
  { code: 43, name: "Austria" },
  { code: 380, name: "Ukraine" },
  { code: 7, name: "Russia" },
  { code: 82, name: "South Korea" },
  { code: 65, name: "Singapore" },
  { code: 60, name: "Malaysia" },
  { code: 66, name: "Thailand" },
  { code: 84, name: "Vietnam" },
  { code: 63, name: "Philippines" },
  { code: 62, name: "Indonesia" },
  { code: 61, name: "Australia" },
  { code: 64, name: "New Zealand" },
  { code: 27, name: "South Africa" },
  { code: 234, name: "Nigeria" },
  { code: 254, name: "Kenya" },
  { code: 20, name: "Egypt" },
  { code: 971, name: "United Arab Emirates" },
  { code: 966, name: "Saudi Arabia" },
  { code: 972, name: "Israel" },
  { code: 90, name: "Turkey" },
  { code: 52, name: "Mexico" },
  { code: 55, name: "Brazil" },
  { code: 54, name: "Argentina" },
  { code: 56, name: "Chile" },
  { code: 57, name: "Colombia" },
  { code: 51, name: "Peru" },
  { code: 58, name: "Venezuela" },
  { code: 593, name: "Ecuador" },
  { code: 595, name: "Paraguay" },
  { code: 598, name: "Uruguay" },
  { code: 591, name: "Bolivia" },
  { code: 507, name: "Panama" },
  { code: 506, name: "Costa Rica" },
  { code: 502, name: "Guatemala" },
  { code: 503, name: "El Salvador" },
  { code: 504, name: "Honduras" },
  { code: 505, name: "Nicaragua" },
  { code: 53, name: "Cuba" },
  { code: 1, name: "Canada" },
];
